target("doctest")
    set_kind("$(kind)")
    add_includedirs(".", {public = true})
    add_headerfiles("*.hpp")
    add_files("doctest.cpp", {public = true, install = true})
    add_files("doctest_impl.cpp")
target_end()

target("doctest_main")
    set_kind("static")
    add_files("main.cpp")
    add_deps("doctest")
    set_default(get_config("with_main"))
target_end()
